<a href="https://colab.research.google.com/github/sourabhadake5100-dev/Sourabh/blob/main/exp5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [647]:
import pandas as pd

url = "https://raw.githubusercontent.com/RimjimRazdan/cars_price_prediction/master/car%20data.csv"

data = pd.read_csv(url)

# Save with the exact filename required by your experiment
data.to_csv("/content/cardata.csv", index=False)

print("cardata.csv downloaded successfully!")
print("Shape:", data.shape)
print(data.head())

cardata.csv downloaded successfully!
Shape: (301, 9)
  Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol
1      sx4  2013           4.75           9.54       43000    Diesel
2     ciaz  2017           7.25           9.85        6900    Petrol
3  wagon r  2011           2.85           4.15        5200    Petrol
4    swift  2014           4.60           6.87       42450    Diesel

  Seller_Type Transmission  Owner
0      Dealer       Manual      0
1      Dealer       Manual      0
2      Dealer       Manual      0
3      Dealer       Manual      0
4      Dealer       Manual      0

In [648]:
data = pd.read_csv('/content/cardata.csv')

In [649]:
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [650]:
data = pd.read_csv("/content/cardata.csv")

data

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [651]:
data.shape

(301, 9)

In [652]:
data.isnull()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
296,False,False,False,False,False,False,False,False,False
297,False,False,False,False,False,False,False,False,False
298,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False
300,False,False,False,False,False,False,False,False,False

In [653]:
data.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [654]:
data.duplicated().sum()

np.int64(2)

In [655]:
df = data.drop_duplicates()

In [656]:
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [657]:
print("\nDuplicate Values")
print(df.duplicated().sum())

Duplicate Values
0

In [658]:
print("\nDuplicate Values")
print(df.duplicated().sum())

Duplicate Values
0

In [659]:
le = LabelEncoder()

In [660]:
data["Fuel_Type"] = le.fit_transform(data["Fuel_Type"])

data["Seller_Type"] = le.fit_transform(data["Seller_Type"])

data["Transmission"] = le.fit_transform(data["Transmission"])

In [661]:
print(data.head())

  Car_Name  Year  Selling_Price  Present_Price  Kms_Driven  Fuel_Type  \
0     ritz  2014           3.35           5.59       27000          2
1      sx4  2013           4.75           9.54       43000          1
2     ciaz  2017           7.25           9.85        6900          2
3  wagon r  2011           2.85           4.15        5200          2
4    swift  2014           4.60           6.87       42450          1

   Seller_Type  Transmission  Owner
0            0             1      0
1            0             1      0
2            0             1      0
3            0             1      0
4            0             1      0

In [662]:
X = data[
    [
        "Year",
        "Present_Price",
        "Kms_Driven",
        "Fuel_Type",
        "Seller_Type",
        "Transmission",
        "Owner"
    ]
]

y = data["Selling_Price"]

In [663]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [664]:
model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [666]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Generate predictions using the trained model first!
y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("R2 Score:", r2)

Mean Absolute Error: 1.2217615462334381
Mean Squared Error: 3.5289272538943877
R2 Score: 0.8468053957655803